### ISSUE TITLE
Runtime error on WebContentView.cpp:615

### ISSUE THREAD

**Issue by blmayer** [SerenityOS/ladybird#138]
After building latest commit, packaging and installing to `/usr/...` I have this runtime error:

```
execvp: No such file or directory
ladybird: /home/blmayer/aur/ladybird-git/src/ladybird/WebContentView.cpp:615: void WebContentView::create_client(): Assertion `false' failed.
QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
WebContent process crashed!
```

The window loads but pages are not rendered.

Maybe the command `DESTDIR="$pkgdir" ninja install -C Build` is missing a library.

**Comment by ADKaster** [comment]
The file it's looking for is bin/WebContent, which is the process that actually loads the web content and renders it back to the GUI application in a shared memory bitmap.

It looks like you built from the Arch AUR, did you use the extra steps I described in https://aur.archlinux.org/packages/ladybird-git#comment-891369 ? 

Those steps created an install tree that looked more or less correct when I built them in a docker container, but I didn't try them in an arch install environment.

**Comment by blmayer** [comment]
Yes I did.

**Comment by ADKaster** [comment]
Is it possible that some other package has a conflict with `/usr/bin/WebContent` ? We didn't exactly name the applications in a way that would play nice with the rest of the linux ecosystem in the same way the `liblagom-*` libraries are.

**Comment by ADKaster** [comment]
As long as the `ninja install` roughly contains the following files it should work? latest commits of both serenity and ladybird would generally be required, they must be in lockstep:

https://gist.github.com/ADKaster/ffc5da20397d0be4f994478617018dc9

**Comment by blmayer** [comment]
I was able to make it run correctly now. Thank you very much! The issue was my ladybird.sh file being in the wrong place. No the PKGBUILD file looks just like yours.

About the font issue: during the install I get this error:

`: Can't translate pathname 'usr/share/res/fonts/CJKBiángRegular36.font' to UTF-8`

I think the character `á` is not in a expected encoding. I will investigate that later.
