### ISSUE TITLE
Cannot create a WebGL context

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/ladybird#16]
Trying to create a WebGL context crashes when trying to load LibSoftGPU:
```
ladybird: /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibGL/GLContext.cpp:1230: AK::NonnullOwnPtr<GL::GLContext> GL::create_context(Gfx::Bitmap&): Assertion `!_temporary_result.is_error()' failed.
```
https://github.com/SerenityOS/serenity/blob/5bbd5e7322f107aae5e62983b5c50c0d01163d57/Userland/Libraries/LibGL/GLContext.cpp#L1230

**Comment by huwdp** [comment]
I don't see this error here (https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/API/WebGL_API/By_example/Clearing_with_colors/_sample_.clearing_the_webgl_context_with_a_solid_color.html) anymore. I guess this has been fixed?
