### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by niutech** [SerenityOS/ladybird#33]
First of all, congratulations on creating a new web browser from scratch!

Could you please provide binary releases for x86(-64) in order to quickly test Ladybird Browser in Linux/Windows? Thanks!

**Comment by ADKaster** [comment]
Hi, please take a look at the rationale for not providing binary packages here:

https://github.com/awesomekling/ladybird/issues/2#issuecomment-1177684116

**Comment by niutech** [comment]
I was able to build Ladybird in WSL2, see the [screenshot](https://i.postimg.cc/rm0ZqhdK/Ladybird-browser.png). It scores 232 points in [HTML5Test](http://html5test.com/s/a5667e5c3b760a8f.html). I even made an AppImage x64 bundle, which you can [download here](https://anonfiles.com/N28dV5zfy2/Ladybird-latest-x86_64_AppImage). Enjoy!

**Comment by threedeyes** [comment]
A build for the Haiku operating system is available in the HaikuDepot -https://depot.haiku-os.org/ladybird
Binary package - https://eu.hpkg.haiku-os.org/haikuports/master/x86_64/current/packages/ladybird-pre20220725-1-x86_64.hpkg

**Comment by 89z** [comment]
Note that "it works with WSL" is not the same thing as "it works with Windows". WSL is essentially a Linux virtual machine running on a Windows computer. Hopefully proper Windows support is planned, but I just wanted to clear up that fact for anyone visiting this page.

**Comment by niutech** [comment]
@89z Nobody said that it works in Windows. I wrote that I've built it in WSL2.

**Comment by 89z** [comment]
@niutech I wasn't saying you made a bad statement. However some people have this idea that WSL == Windows, so I like to clear that up when possible.

**Comment by guihkx** [comment]
Just a heads up for Arch Linux users: Ladybird now has an [official package](https://archlinux.org/packages/community/x86_64/ladybird/)!

**Comment by linusg** [comment]
No official binary releases planned, folks are of course welcome to redistribute their own builds.

**Comment by 89z** [comment]
> Additionally, the Serenity LibWeb does not currently compile on Windows. If you want to compile on a Windows machine, you should use WSL2.

To add to this, I just received confirmation in another issue, that native Windows support is not planned, so it could be several years, if ever, for that to be realized.

**Comment by niutech** [comment]
There is [cosmogfx](https://github.com/jacereda/cosmogfx) library based on Cosmopolitan Libc which builds cross-platform single-file graphical apps. Maybe it can help?
