### ISSUE TITLE
Text selection not working

### ISSUE THREAD

**Issue by yeppiidev** [SerenityOS/ladybird#42]
Unable to select text on any website. I think this feature is implemented but it currently doesn't work.

**Comment by elcuco** [comment]
I just loaded http://en.wikipedia.org - and clicked an item. I can clearly select... yap, the main text is not selected, but the sidebar text.. 

Nothing new broke here. IMHO, we can close this issue.

**Comment by yeppiidev** [comment]
alright I guess...?
