### ISSUE TITLE
UX features request

### ISSUE THREAD

**Issue by GHNewbiee** [SerenityOS/ladybird#57]
I do know that it's very early for feature requests but I couldn't resist the temptation to suggest the following *extra-principle UX features* to be considered for being developed **in-house**.

1) **Built-in multi-row tabbing** ie tabs can be placed in more than one horizontal rows where both the number of tabs per row and the number of rows can be set by the user
2) **Built-in (tab) session manager** which will support multi-level nesting categories/groups
3) **Built-in tab locking and unloading**

*Tia*

**Comment by awesomekling** [comment]
Like all projects in the SerenityOS family, Ladybird has [no interest in feature requests from non-contributors](https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy). Closing :)
