### ISSUE TITLE
sys/cdefs.h is non-standard

### ISSUE THREAD

**Issue by ddevault** [SerenityOS/ladybird#61]
```
/usr/include/sys/cdefs.h:1:2: error: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Werror=cpp]
    1 | #warning usage of non-standard #include <sys/cdefs.h> is deprecated
      |  ^~~~~~~
```

**Comment by ADKaster** [comment]
Which header did this come from? Was it LibThreading/ConditionVariable.h or somewhere else?

If it was, a cleanup PR to https://github.com/SerenityOS/serenity to remove that header and sys/types.h would be much appreciated. That header should only be included from libraries that are serenity-only.

**Comment by ddevault** [comment]
Appears to have come from regex-related stuff. Did not look into it too deeply, feel free to close if this isn't useful.

**Comment by ADKaster** [comment]
Ah hm. LibRegex seems to include LibC/regex.h. that's ... not ideal. This is really an issue with Serenity though, rather than ladybird.

**Comment by linusg** [comment]
This was fixed in https://github.com/SerenityOS/serenity/pull/15288.
